# Generated by Django 6.0.5 on 2026-05-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=200)),
                ('house_address', models.CharField(max_length=200)),
                ('house_description', models.TextField()),
                ('house_type', models.CharField(max_length=200)),
                ('house_size', models.CharField(max_length=200)),
                ('house_height', models.CharField(max_length=200)),
                ('house_position', models.CharField(max_length=200)),
                ('total_price', models.CharField(max_length=200)),
                ('unit_price', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'db_table': 'house_listing',
            },
        ),
        migrations.CreateModel(
            name='FavoriteHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('house_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.houselisting')),
            ],
            options={
                'verbose_name': '收藏房源',
                'verbose_name_plural': '收藏房源',
                'db_table': 'favorite_house',
            },
        ),
    ]
