# Generated by Django 6.0.5 on 2026-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='house_image',
            field=models.CharField(default='house_default.jpg', max_length=200),
        ),
    ]
