# Generated by Django 6.0.5 on 2026-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_houselisting_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='house_image',
            field=models.CharField(default='house_image/house_default.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='house_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='total_price',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='unit_price',
            field=models.FloatField(max_length=200),
        ),
    ]
