# Generated by Django 6.0.5 on 2026-05-25 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='请输入11位手机号', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
    ]
